---

- name: Add system groups
  group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
  with_items: "{{ base_add_groups }}"

- name: Add per-user groups
  group:
    name: "{{ item.username }}"
    gid: "{{ item.uid | default(omit) }}"
  with_items: "{{ base_users }}"
  when: base_per_user_groups
